apiVersion: apps/v1
kind: Deployment
metadata:
  name: techiescamp-app
  labels:
    app: webserver
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: techiescamp
          image: nginx:1.18.0
          ports:
            - containerPort: 80